version: '3'
services:
  eureka01:
    image: registry.united-iot.com/test/eureka-server:latest
    deploy:
      placement:
        constraints: [node.role != manager]
    command: java -jar eureka-server.jar --eureka.instance.hostname=eureka01 --eureka.client.serviceUrl.defaultZone=http://eureka02:8761/eureka/,http://eureka03:8761/eureka/
    networks:
      - iot
    ports:
      - "8761:8761"
  eureka02:
    image: registry.united-iot.com/test/eureka-server:latest
    deploy:
      placement:
        constraints: [node.role != manager]
    command: java -jar eureka-server.jar --eureka.instance.hostname=eureka02 --eureka.client.serviceUrl.defaultZone=http://eureka01:8761/eureka/,http://eureka03:8761/eureka/
    networks:
      - iot
    ports:
      - "8762:8761"
  eureka03:
    image: registry.united-iot.com/test/eureka-server:latest
    deploy:
      placement:
        constraints: [node.role != manager]
    command: java -jar eureka-server.jar --eureka.instance.hostname=eureka03 --eureka.client.serviceUrl.defaultZone=http://eureka01:8761/eureka/,http://eureka02:8761/eureka/
    networks:
      - iot
    ports:
      - "8763:8761"
networks:
  iot:
    external: true
